Migrate to pytest (#73)
Since nose is too outdated to support Python 3.10
```
  File "/Users/czhang/workspace/vendor/flask_injector/ve3.10/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```


Co-authored-by: ZHANG Cheng <czhang.oss@gmail.com>